export const LOGIN_ACTION = 'LOGIN_ACTION'
export const REGISTER_ACTION = 'REGISTER_ACTION'
// 结构名
export const GETUSEINFO_ACTION = 'GETUSEINFO_ACTION'
export const ADDSTUDENT_ACTION = 'ADDSTUDENT_ACTION'
export const GETSTUDENTINFO_ACTION = 'GETSTUDENTINFO_ACTION'
export const ADDSTUDENTHEIGHT_ACTION = 'ADDSTUDENTHEIGHT_ACTION'
export const EDITSTUDENTHEIGHT_ACTION = 'EDITSTUDENTHEIGHT_ACTION'
export const GETSTUDENTDETAI_ACTION = 'GETSTUDENTDETAI_ACTION'

export const ADDSTUDENTHW_ACTION = 'ADDSTUDENTHW_ACTION'
export const ADDSTUDENTSCORE_ACTION = 'ADDSTUDENTSCORE_ACTION'
export const ADDSTUDENTLEAVE_ACTION = 'ADDSTUDENTLEAVE_ACTION'

export const ADDSTUDENTCOMPLAINT_ACTION = 'ADDSTUDENTCOMPLAINT_ACTION'
export const EDITSTUDENTCOMPLAINT_ACTION = 'EDITSTUDENTCOMPLAINT_ACTION'

export const ADDSTUDENTHWORK_ACTION = 'ADDSTUDENTHWORK_ACTION'
export const EDITSTUDENTHWORK_ACTION = 'EDITSTUDENTHWORK_ACTION'
